### ISSUE TITLE
ValueError: Cannot set a DataFrame with multiple columns to the single column dist

### ISSUE THREAD

**Issue by coding-dallas** [ncsoft/PhonMatchNet#2]
The following is the error trace while running train.py

> Preparing noise DB
>> Convert word to phoneme
>> Convert speech word to phoneme
>> Convert phoneme to index
>> Convert speech phoneme to index
>> Compute phoneme embedding
>> Calucate Edit distance ratio
Traceback (most recent call last):
  File "/home/kesavaraj/Documents/kesav/Research/PhonMatchNet/train.py", line 62, in <module>
    train_dataset = libriphrase.LibriPhraseDataloader(batch_size=GLOBAL_BATCH_SIZE, features=text_input, train=True, types='both', shuffle=True, pkl=args.train_pkl)
  File "/home/kesavaraj/Documents/kesav/Research/PhonMatchNet/dataset/libriphrase.py", line 66, in __init__
    self.__prep__()
  File "/home/kesavaraj/Documents/kesav/Research/PhonMatchNet/dataset/libriphrase.py", line 123, in __prep__
    self.data['dist'] = self.data.apply(lambda x: Levenshtein.ratio(re.sub(r"[^a-zA-Z0-9]+", ' ', x['wav_label']), re.sub(r"[^a-zA-Z0-9]+", ' ', x['text'])), axis=1)
  File "/home/kesavaraj/miniconda3/envs/tf/lib/python3.9/site-packages/pandas/core/frame.py", line 3940, in __setitem__
    self._set_item_frame_value(key, value)
  File "/home/kesavaraj/miniconda3/envs/tf/lib/python3.9/site-packages/pandas/core/frame.py", line 4094, in _set_item_frame_value
    raise ValueError(
ValueError: Cannot set a DataFrame with multiple columns to the single column dist

This is pointing to the line 123 in libriphrase.py. The following is the code
**print(">> Calucate Edit distance ratio")
            self.data['dist'] = self.data.apply(lambda x: Levenshtein.ratio(re.sub(r"[^a-zA-Z0-9]+", ' ', x['wav_label']), re.sub(r"[^a-zA-Z0-9]+", ' ', x['text'])), axis=1)**

Here column is not specified in self.data.apply(). what column name should be included?

**Comment by LeeYongHyeok** [comment]
Hi @coding-dallas,

This code calculates the Normalized Levenshtein distance between pairs of "wav_label" and "text". This part seems unrelated to training, so it can be commented out.

**Comment by coding-dallas** [comment]
Thank you for the response
